"""Client for the rentry.co API.

The /api endpoints are CSRF-exempt: no csrf token, cookies or Referer header
are needed. Every method returns the parsed JSON response as a dict with at
least 'status' and 'content' keys ('status' is '200' on success).
"""

import json
import urllib.parse
import urllib.request


class RentryClient:
    """Thin client for the rentry.co API. Works against any rentry instance via base_url."""

    def __init__(self, base_url='https://rentry.co'):
        self.base_url = base_url.rstrip('/')

    def new(self, text, url=None, edit_code=None, metadata=None):
        """Create a new page. url and edit_code are generated by the server if not given.

        metadata may be a newline-separated string ('OPTION = value') or a dict.
        """
        payload = {'text': text}
        if url is not None:
            payload['url'] = url
        if edit_code is not None:
            payload['edit_code'] = edit_code
        if metadata is not None:
            payload['metadata'] = self._encode_metadata(metadata)
        return self._post('/api/new', payload)

    def edit(self, url, edit_code, text=None, metadata=None, update_mode=None,
             update_secret_metadata=None, new_url=None, new_edit_code=None,
             new_modify_code=None):
        """Edit an existing page. edit_code may also be a modify code ('m:...').

        update_mode: 'upsert' changes only the metadata options provided and keeps
            the rest; default is a full replacement of text and metadata.
        update_secret_metadata: previously-set SECRET_* metadata is preserved by
            default no matter what the edit sends. Pass True to allow this edit to
            change or remove it.
        new_modify_code: provide 'm:' to unset an existing modify code.
        """
        payload = {'edit_code': edit_code}
        if text is not None:
            payload['text'] = text
        if metadata is not None:
            payload['metadata'] = self._encode_metadata(metadata)
        if update_mode is not None:
            payload['update_mode'] = update_mode
        if update_secret_metadata is not None:
            payload['update_secret_metadata'] = 'true' if update_secret_metadata else 'false'
        if new_url is not None:
            payload['new_url'] = new_url
        if new_edit_code is not None:
            payload['new_edit_code'] = new_edit_code
        if new_modify_code is not None:
            payload['new_modify_code'] = new_modify_code
        return self._post('/api/edit/{}'.format(url), payload)

    def fetch(self, url, edit_code):
        """Fetch a page's full details (text, metadata, views, dates...)."""
        return self._post('/api/fetch/{}'.format(url), {'edit_code': edit_code})

    def delete(self, url, edit_code):
        """Delete a page. Requires the edit code (not a modify code)."""
        return self._post('/api/delete/{}'.format(url), {'edit_code': edit_code})

    def raw(self, url, auth_code=None):
        """Get a page's raw markdown text.

        auth_code is a rentry-auth access code (from support@rentry.co), or the
        page's own SECRET_RAW_ACCESS_CODE value.
        """
        headers = {'rentry-auth': auth_code} if auth_code is not None else {}
        return self._get('/api/raw/{}'.format(url), headers)

    @staticmethod
    def _encode_metadata(metadata):
        if isinstance(metadata, dict):
            return json.dumps(metadata)
        return metadata

    def _post(self, path, payload):
        data = urllib.parse.urlencode(payload).encode()
        request = urllib.request.Request(self.base_url + path, data)
        return self._request(request)

    def _get(self, path, headers={}):
        request = urllib.request.Request(self.base_url + path, headers=headers)
        return self._request(request)

    @staticmethod
    def _request(request):
        with urllib.request.urlopen(request) as response:
            return json.loads(response.read().decode('utf-8'))
